### ISSUE TITLE
graffiti-todo blog post?

### ISSUE THREAD

**Issue by SOSANA** [RisingStack/graffiti-todo#1]
curious if there was a blog post discussing this implementation.

love your guys work! thanks

**Comment by tothandras** [comment]
Hi @SOSANA!
There will be an upcoming blog post, we made this app to demonstrate the Relay compatibility of `graffiti-mongoose`. There are still a few things we like to add to `graffiti` and `graffiti-mongoose` before we publish it.

**Comment by SOSANA** [comment]
Thank you so much for replying!! I am putting the pieces together slowly but really excited about developing some projects with `graffiti-mongoose` is there a road-map I could check out to find out what needs to be done?

**Comment by tothandras** [comment]
@SOSANA Check out the [`graffiti-mongoose` example](https://github.com/RisingStack/graffiti-mongoose/tree/master/example). We put together a readme, including example queries you can try out by yourself.

**Comment by SOSANA** [comment]
Thanks @tothandras 

I will now close this issue

**Comment by SOSANA** [comment]
Thanks @tothandras

I will now close this issue
