### ISSUE TITLE
Isomorphic/Universal example?

### ISSUE THREAD

**Issue by mtsewrs** [RisingStack/graffiti-todo#3]
I would like to know if it's possible to make this app Universal. I've been using Graffiti with https://github.com/jedireza/hapi-react-views and tried to get relay to work on the server with https://github.com/denvned/isomorphic-relay but I am totally lost!

Help would be much appreciated!

**Comment by mtsewrs** [comment]
Also, is it recommended to not go universal with relay and graphql?

**Comment by hekike** [comment]
@mattiasewers hi. Graffiti is providing a Graphql server out of the box from your db schema. So it's providing a standard relay API. There is nothing to do to make it universal/isomorphic. It's just an API for your app.

To creating an isormorphic todo mvc check these examples:
https://github.com/search?utf8=%E2%9C%93&q=isomorphic+todomvc&type=Repositories&ref=searchresults

**Comment by mtsewrs** [comment]
@hekike I ment this example... but anyway, how did you generate the schema.json for the babel plugin?

**Comment by tothandras** [comment]
@mattiasewers `npm run update-schema`

**Comment by mtsewrs** [comment]
@tothandras of course... Thanks!
